[theme]
name = "solarized-dark"

[icons]
name = "awesome"

[[block]]
block = "net"
device = "ens9"
interval = 2
hide_inactive = true
hide_missing = true
format = "{ip} {speed_up} {speed_down}"

[[block]]
block = "net"
device = "wlan0"
interval = 2
format = "{ssid} {ip} {speed_up} {speed_down}"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 60
warning = 6
alert = 3

[[block]]
block = "disk_space"
path = "/home/"
alias = "🏠"
info_type = "available"
unit = "GB"
interval = 60
warning = 20
alert = 10

# [[block]]
# block = "memory"
# display_type = "memory"
# format_mem = "{Mup}%"
# format_swap = "{SUp}%"

[[block]]
block = "temperature"
interval = 10
collapsed = true

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

# [[block]]
# block = "pacman"
# interval = 3600

[[block]]
block = "battery"

interval = 60

[[block]]
block = "sound"

[[block]]
block = "weather"
[block.service]
name = "openweathermap"
api_key = "35ee3a1b9a02aa4ab66866c43bc10d54"
units = "metric"
city_id = "2158177"

[[block]]
block = "time"
interval = 10
format = "%Y-%m-%d %H:%M+00"
timezone = "UTC"

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"
