[symlinks]
"bash/bash_profile" = "/home/josh/.bash_profile"
"bash/bashrc" = "/home/josh/.bashrc"
"fontconfig/conf.d/40-monospace.conf" = "/home/josh/.config/fontconfig/conf.d/40-monospace.conf"
"fontconfig/conf.d/40-sans-serif.conf" = "/home/josh/.config/fontconfig/conf.d/40-sans-serif.conf"
"fontconfig/conf.d/40-serif.conf" = "/home/josh/.config/fontconfig/conf.d/40-serif.conf"
"general/environment.d/10-xdg.conf" = "/home/josh/.config/environment.d/10-xdg.conf"
"general/environment.d/90-python.conf" = "/home/josh/.config/environment.d/90-python.conf"
"general/environment.d/90-rust.conf" = "/home/josh/.config/environment.d/90-rust.conf"
"general/home-josh-media-cxin.mount" = "/home/josh/.config/systemd/user/home-josh-media-cxin.mount"
"general/home-josh-media-macbook.automount" = "/home/josh/.config/systemd/user/home-josh-media-macbook.automount"
"general/home-josh-media-macbook.mount" = "/home/josh/.config/systemd/user/home-josh-media-macbook.mount"
"general/polkit-gnome-authentication-agent.service" = "/home/josh/.config/systemd/user/polkit-gnome-authentication-agent.service"
"general/profile" = "/home/josh/.profile"
"general/sshconfig" = "/home/josh/.ssh/config"
"git/attributes" = "/home/josh/.config/git/attributes"
"git/ipynb_output_filter.py" = "/home/josh/.config/git/ipynb_output_filter.py"
"gpg/gpg-agent.conf" = "/home/josh/.gnupg/gpg-agent.conf"
"gpg/sshcontrol" = "/home/josh/.gnupg/sshcontrol"
"kitty/dark.theme.conf" = "/home/josh/.config/kitty/dark.theme.conf"
"kitty/kitty.conf" = "/home/josh/.config/kitty/kitty.conf"
"kitty/light.theme.conf" = "/home/josh/.config/kitty/light.theme.conf"
"mopidy/mopidy.conf" = "/home/josh/.config/mopidy/mopidy.conf"
"sway/background.png" = "/home/josh/.config/sway/background.png"
"sway/mako" = "/home/josh/.config/mako/config"
"sway/mako.service" = "/home/josh/.config/systemd/user/mako.service"
"sway/sway-session.target" = "/home/josh/.config/systemd/user/sway-session.target"
"sway/swayidle.service" = "/home/josh/.config/systemd/user/swayidle.service"
"sway/swaylock" = "/home/josh/.config/sway/swaylock"
"sway/udiskie.service" = "/home/josh/.config/systemd/user/udiskie.service"
"sway/udiskie.yml" = "/home/josh/.config/udiskie/config.yml"
"sway/waybar.css" = "/home/josh/.config/waybar/style.css"
"sway/waybar.json" = "/home/josh/.config/waybar/config"
"sway/waybar.service" = "/home/josh/.config/systemd/user/waybar.service"

[templates]
"general/environment.d/10-applications.conf" = "/home/josh/.config/environment.d/10-applications.conf"
"general/environment.d/90-make.conf" = "/home/josh/.config/environment.d/90-make.conf"
"git/config" = "/home/josh/.config/git/config"
"sway/config" = "/home/josh/.config/sway/config"
