[bash]
    [bash.files]
    "bash/bash_profile" = "~/.bash_profile"
    "bash/bashrc"       = "~/.bashrc"

[bin]
    [bin.files]
    "bin/screen-share"   = "~/.local/bin/screen-share"
    "bin/transcode-hevc" = "~/.local/bin/transcode-hevc"

[borgmatic]
    [borgmatic.files]
    "borgmatic/borgmatic.service" = "~/.local/share/systemd/user/borgmatic.service"
    "borgmatic/borgmatic.timer"   = "~/.local/share/systemd/user/borgmatic.timer"
    "borgmatic/config.yaml"       = "~/.config/borgmatic/config.yaml"
    "borgmatic/patterns"          = "~/.config/borgmatic/patterns"

[doom]
    [doom.files]
    "doom/config.org"   = "~/.config/doom/config.org"
    "doom/init.el"      = "~/.config/doom/init.el"
    "doom/packages.el"  = "~/.config/doom/packages.el"
    "doom/packages.org" = "~/.config/doom/packages.org"

    [doom.variables]
    "email" = "josh@jpellis.me"
    "name"  = "JP-Ellis"

[fonts]
    [fonts.files]
    "fontconfig/conf.d/40-monospace.conf"  = "~/.config/fontconfig/conf.d/40-monospace.conf"
    "fontconfig/conf.d/40-sans-serif.conf" = "~/.config/fontconfig/conf.d/40-sans-serif.conf"
    "fontconfig/conf.d/40-serif.conf"      = "~/.config/fontconfig/conf.d/40-serif.conf"

[general]
    [general.files]
    "general/profile"   = "~/.profile"
    "general/sshconfig" = "~/.ssh/config"

    "general/environment.d/10-applications.conf" = "~/.config/environment.d/10-applications.conf"
    "general/environment.d/10-xdg.conf"          = "~/.config/environment.d/10-xdg.conf"
    "general/environment.d/90-aws.conf"          = "~/.config/environment.d/90-aws.conf"
    "general/environment.d/90-bundle.conf"       = "~/.config/environment.d/90-bundle.conf"
    "general/environment.d/90-calc.conf"         = "~/.config/environment.d/90-calc.conf"
    "general/environment.d/90-gnupg.conf"        = "~/.config/environment.d/90-gnupg.conf"
    "general/environment.d/90-go.conf"           = "~/.config/environment.d/90-go.conf"
    "general/environment.d/90-grip.conf"         = "~/.config/environment.d/90-grip.conf"
    "general/environment.d/90-java.conf"         = "~/.config/environment.d/90-java.conf"
    "general/environment.d/90-make.conf"         = "~/.config/environment.d/90-make.conf"
    "general/environment.d/90-mathematica.conf"  = "~/.config/environment.d/90-mathematica.conf"
    "general/environment.d/90-minikube.conf"     = "~/.config/environment.d/90-minikube.conf"
    "general/environment.d/90-nodejs.conf"       = "~/.config/environment.d/90-nodejs.conf"
    "general/environment.d/90-parallel.conf"     = "~/.config/environment.d/90-parallel.conf"
    "general/environment.d/90-python.conf"       = "~/.config/environment.d/90-python.conf"
    "general/environment.d/90-rust.conf"         = "~/.config/environment.d/90-rust.conf"
    "general/environment.d/90-sqlite.conf"       = "~/.config/environment.d/90-sqlite.conf"
    "general/environment.d/90-texlive.conf"      = "~/.config/environment.d/90-texlive.conf"

    "general/borgmatic.service"                 = "~/.config/systemd/user/borgmatic.service"
    "general/borgmatic.timer"                   = "~/.config/systemd/user/borgmatic.timer"
    "general/home-josh-media-cxin.mount"        = "~/.config/systemd/user/home-josh-media-cxin.mount"
    "general/home-josh-media-macbook.automount" = "~/.config/systemd/user/home-josh-media-macbook.automount"
    "general/home-josh-media-macbook.mount"     = "~/.config/systemd/user/home-josh-media-macbook.mount"
    "general/monitor-transmission.service"      = "~/.config/systemd/user/monitor-transmission.service"
    "general/monitor-transmission.timer"        = "~/.config/systemd/user/monitor-transmission.timer"
    "general/monitor-transmission.zsh"          = "~/.config/systemd/user/monitor-transmission.zsh"
    "general/rustup-update.service"             = "~/.config/systemd/user/rustup-update.service"
    "general/rustup-update.timer"               = "~/.config/systemd/user/rustup-update.timer"
    "general/standing-desk-reminder.service"    = "~/.config/systemd/user/standing-desk-reminder.service"
    "general/standing-desk-reminder.timer"      = "~/.config/systemd/user/standing-desk-reminder.timer"

    [general.variables]
    app-browser = "brave"
    app-editor  = "vim"
    app-pager   = "less"
    app-visual  = "code -w"
    nproc       = 12
    tmpdir      = "/tmp/josh"

[git]
    [git.files]
    "git/attributes"             = "~/.config/git/attributes"
    "git/config"                 = "~/.config/git/config"
    "git/ipynb_output_filter.py" = "~/.config/git/ipynb_output_filter.py"

    [git.variables]
    signingKey = "josh@jpellis.me"
    usernameGithub = "JP-Ellis"
    usernameGitlab = "JP-Ellis"

[gpg]
    [gpg.files]
    "gpg/gpg-agent.conf" = "~/.local/share/gnupg/gpg-agent.conf"
    "gpg/sshcontrol"     = "~/.local/share/gnupg/sshcontrol"

[kitty]
    [kitty.files]
    "kitty/dark.theme.conf"  = "~/.config/kitty/dark.theme.conf"
    "kitty/kitty.conf"       = "~/.config/kitty/kitty.conf"
    "kitty/light.theme.conf" = "~/.config/kitty/light.theme.conf"

[mathematica]
    [mathematica.files]
    "Mathematica/Kernel.m" = { target = "~/.config/mathematica/Kernel/init.m", type = "symbolic" }

[mopidy]
    [mopidy.files]
    "mopidy/mopidy.conf" = "~/.config/mopidy/mopidy.conf"

[sheldon]
    [sheldon.files]

[sway]
    [sway.files]
    "sway/background.png"                            = "~/.config/sway/background.png"
    "sway/config"                                    = "~/.config/sway/config"
    "sway/mako"                                      = "~/.config/mako/config"
    "sway/mako.service"                              = "~/.config/systemd/user/mako.service"
    "sway/polkit-gnome-authentication-agent.service" = "~/.config/systemd/user/polkit-gnome-authentication-agent.service"
    "sway/sway-session.target"                       = "~/.config/systemd/user/sway-session.target"
    "sway/swayidle.service"                          = "~/.config/systemd/user/swayidle.service"
    "sway/swaylock"                                  = "~/.config/sway/swaylock"
    "sway/udiskie.service"                           = "~/.config/systemd/user/udiskie.service"
    "sway/udiskie.yml"                               = "~/.config/udiskie/config.yml"
    "sway/waybar.css"                                = "~/.config/waybar/style.css"
    "sway/waybar.json"                               = "~/.config/waybar/config"
    "sway/waybar.service"                            = "~/.config/systemd/user/waybar.service"

    [sway.variables]
    terminal = "kitty"

[windows-terminal]
    [windows-terminal.files]
    "windows-terminal/settings.json" = "~/AppData/Local/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe/LocalState/settings.json"

[zsh]
    [zsh.files]
    "zsh/sheldon-update.service" = "~/.config/systemd/user/sheldon-update.service"
    "zsh/sheldon-update.timer"   = "~/.config/systemd/user/sheldon-update.timer"
    "zsh/sheldon.toml"           = { target = "~/.config/sheldon/plugins.toml", type = "symbolic" }
    "zsh/zshrc"                  = "~/.zshrc"
