# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more
# <https://github.com/rossmacarthur/sheldon#readme>

shell = "zsh"

################################################################################
[templates]
# Use `zsh-defer` to source files once the shell is ready.
# See <https://github.com/romkatv/zsh-defer>
#
# This relies on the `zsh-defer` plugin being loaded first.
defer = """
{{ hooks?.pre | nl }}
{% for file in files %}
    zsh-defer source "{{ file }}"
{% endfor %}
{{ hooks?.post | nl }}
"""

################################################################################
[plugins]

[plugins.zsh-defer]
# As this plugin is used to defer the loading of other plugins, it must
# be loaded first so as to be available.
github = "romkatv/zsh-defer"

[plugins.colors]
inline = "autoload -Uz colors && zsh-defer colors"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply  = ["defer"]

[plugins.enhancd]
github = "babarot/enhancd"
apply  = ["defer"]
[plugins.enhancd.hooks]
pre = """
export ENHANCD_DIR="$HOME/.config/enhancd"
export ENHANCD_FILTER=fzf:fzy
export ENHANCED_HOOK_AFTER_CD=ls
export ENHANCD_USE_ABBREV=true
"""

## The following plugins need to be loaded last as they wrap other widgets

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply  = ["defer"]

[plugins.zsh-autocomplete]
# This will execute `compinit` and `autoload -Uz compinit` for you.
github = "marlonrichert/zsh-autocomplete"
apply  = ["defer"]
[plugins.zsh-autocomplete.hooks]
pre = """
# Always search history in default context
zstyle ':autocomplete:*' default-context history-incremental-search-backward
zstyle ':autocomplete:*' min-input 3

# Insert prefixes shared by all completions
zstyle ':autocomplete:*:*' insert-unambiguous yes
"""
post = """
# Tab accepts the completion, Enter executes the completion
zsh-defer bindkey -M menuselect '\\r' .accept-line
"""
