## See gpg-agent.socket.conf for why the socket path is hashed.
##
## Regenerate the path with: gpgconf --list-dirs agent-browser-socket
[Socket]
ListenStream=
ListenStream=%t/gnupg/d.kzge3rbrzdd3u1q6rx3ujnqj/S.gpg-agent.browser
